[pytest]
# pytest tests/  --html-report=./report --title='PYTEST REPORT' 
markers =
    webtest: mark a test as a webtest
    slow: mark test as slow
	smoke:  quick health-check tests
    sanity: mark test as sanity
	regression: full end-to-end suite
    functional: mark test as functional
	uat: These test are only to test in UAT
	prod: These test are only to test in PROD


